name: moro
channels:
  - pytorch
  - nvidia
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - aiohappyeyeballs=2.4.4
  - aiohttp=3.11.10
  - aiosignal=1.2.0
  - aom=3.9.1
  - blas=1.0
  - braceexpand=0.1.7
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - ca-certificates=2025.2.25
  - cairo=1.18.0
  - certifi=2025.1.31
  - charset-normalizer=3.3.2
  - click=8.1.8
  - cuda-cudart=12.1.105
  - cuda-cupti=12.1.105
  - cuda-libraries=12.1.0
  - cuda-nvrtc=12.1.105
  - cuda-nvtx=12.1.105
  - cuda-opencl=12.8.90
  - cuda-runtime=12.1.0
  - cuda-version=12.8
  - dav1d=1.2.1
  - expat=2.7.0
  - ffmpeg=7.0.1
  - filelock=3.17.0
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.14.2
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - freetype=2.13.3
  - fribidi=1.0.10
  - frozenlist=1.5.0
  - fsspec=2024.12.0
  - giflib=5.2.2
  - gmp=6.3.0
  - gmpy2=2.2.1
  - gnutls=3.7.9
  - graphite2=1.3.13
  - harfbuzz=8.5.0
  - icu=73.2
  - idna=3.7
  - intel-openmp=2023.1.0
  - jinja2=3.1.6
  - jpeg=9e
  - lame=3.100
  - lcms2=2.16
  - ld_impl_linux-64=2.40
  - lerc=4.0.0
  - level-zero=1.24.1
  - libabseil=20240116.2
  - libass=0.17.1
  - libcublas=12.1.0.26
  - libcufft=11.0.2.4
  - libcufile=1.13.1.3
  - libcurand=10.3.9.90
  - libcusolver=11.4.4.55
  - libcusparse=12.0.2.55
  - libdeflate=1.22
  - libdrm=2.4.124
  - libexpat=2.7.0
  - libffi=3.4.4
  - libgcc=15.1.0
  - libgcc-ng=15.1.0
  - libglib=2.80.2
  - libgomp=15.1.0
  - libhwloc=2.11.2
  - libiconv=1.18
  - libidn2=2.3.4
  - libjpeg-turbo=2.0.0
  - libnpp=12.0.2.50
  - libnsl=2.0.1
  - libnvjitlink=12.1.105
  - libnvjpeg=12.1.1.14
  - libopenvino=2024.1.0
  - libopenvino-auto-batch-plugin=2024.1.0
  - libopenvino-auto-plugin=2024.1.0
  - libopenvino-hetero-plugin=2024.1.0
  - libopenvino-intel-cpu-plugin=2024.1.0
  - libopenvino-intel-gpu-plugin=2024.1.0
  - libopenvino-intel-npu-plugin=2024.1.0
  - libopenvino-ir-frontend=2024.1.0
  - libopenvino-onnx-frontend=2024.1.0
  - libopenvino-paddle-frontend=2024.1.0
  - libopenvino-pytorch-frontend=2024.1.0
  - libopenvino-tensorflow-frontend=2024.1.0
  - libopenvino-tensorflow-lite-frontend=2024.1.0
  - libopus=1.5.2
  - libpciaccess=0.18
  - libpng=1.6.39
  - libprotobuf=4.25.3
  - libsqlite=3.46.0
  - libstdcxx=15.1.0
  - libstdcxx-ng=13.2.0
  - libtasn1=4.19.0
  - libtiff=4.7.0
  - libunistring=0.9.10
  - libuuid=2.38.1
  - libva=2.21.0
  - libvpx=1.14.1
  - libwebp=1.3.2
  - libwebp-base=1.3.2
  - libxcb=1.15
  - libxml2=2.13.8
  - libzlib=1.2.13
  - lightning=2.5.0.post0
  - lightning-utilities=0.11.9
  - llvm-openmp=14.0.6
  - lz4-c=1.9.4
  - markupsafe=3.0.2
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.11
  - mkl_random=1.2.8
  - mpc=1.3.1
  - mpfr=4.2.1
  - mpmath=1.3.0
  - multidict=6.1.0
  - ncurses=6.4
  - nettle=3.9.1
  - networkx=3.4.2
  - numpy=2.0.1
  - numpy-base=2.0.1
  - ocl-icd=2.3.2
  - openh264=2.4.1
  - openjpeg=2.5.2
  - openssl=3.0.16
  - p11-kit=0.24.1
  - packaging=24.2
  - pcre2=10.43
  - pillow=11.1.0
  - pip=25.0
  - pixman=0.46.0
  - propcache=0.3.1
  - pthread-stubs=0.4
  - pugixml=1.14
  - pysocks=1.7.1
  - python=3.11.0
  - python_abi=3.11
  - pytorch=2.5.1
  - pytorch-cuda=12.1
  - pytorch-lightning=2.5.0.post0
  - pytorch-mutex=1.0
  - pyyaml=6.0.2
  - readline=8.2
  - requests=2.32.3
  - setuptools=75.8.0
  - snappy=1.2.1
  - sqlite=3.45.3
  - svt-av1=2.1.0
  - tbb=2021.13.0
  - tk=8.6.14
  - torchaudio=2.5.1
  - torchmetrics=1.2.1
  - torchtriton=3.1.0
  - torchvision=0.20.1
  - tqdm=4.67.1
  - typing-extensions=4.12.2
  - typing_extensions=4.12.2
  - urllib3=2.3.0
  - wheel=0.45.1
  - x264=1!164.3095
  - x265=3.5
  - xorg-fixesproto=5.0
  - xorg-kbproto=1.0.7
  - xorg-libice=1.1.2
  - xorg-libsm=1.2.6
  - xorg-libx11=1.8.9
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xorg-libxext=1.3.4
  - xorg-libxfixes=5.0.3
  - xorg-libxrender=0.9.11
  - xorg-renderproto=0.11.1
  - xorg-xextproto=7.3.0
  - xorg-xproto=7.0.31
  - xz=5.6.4
  - yacs=0.1.6
  - yaml=0.2.5
  - yarl=1.18.0
  - zlib=1.2.13
  - zstd=1.5.6
  - pip:
      - addict==2.4.0
      - albucore==0.0.23
      - albumentations==1.3.1
      - annotated-types==0.7.0
      - antlr4-python3-runtime==4.9.3
      - asttokens==3.0.0
      - attrs==25.3.0
      - blinker==1.9.0
      - chumpy==0.70
      - comm==0.2.2
      - configargparse==1.7
      - contourpy==1.3.2
      - cycler==0.12.1
      - dash==3.0.3
      - decorator==5.2.1
      - docker-pycreds==0.4.0
      - einops==0.8.1
      - executing==2.2.0
      - fastjsonschema==2.21.1
      - flask==3.0.3
      - fonttools==4.57.0
      - freetype-py==2.5.1
      - gitdb==4.0.12
      - gitpython==3.1.44
      - huggingface-hub==0.30.2
      - hydra-core==1.3.2
      - imageio==2.37.0
      - importlib-metadata==8.6.1
      - iopath==0.1.10
      - ipython==9.1.0
      - ipython-pygments-lexers==1.1.1
      - ipywidgets==8.1.6
      - itsdangerous==2.2.0
      - jedi==0.19.2
      - joblib==1.4.2
      - jsonschema==4.23.0
      - jsonschema-specifications==2024.10.1
      - jupyter-core==5.7.2
      - jupyterlab-widgets==3.0.14
      - kiwisolver==1.4.8
      - lap==0.5.12
      - lazy-loader==0.4
      - loguru==0.7.3
      - matplotlib==3.10.1
      - matplotlib-inline==0.1.7
      - narwhals==1.35.0
      - nbformat==5.10.4
      - nest-asyncio==1.6.0
      - omegaconf==2.3.0
      - open3d==0.19.0
      - opencv-python==4.11.0.86
      - opencv-python-headless==4.11.0.86
      - pandas==2.2.3
      - parso==0.8.4
      - pexpect==4.9.0
      - platformdirs==4.3.7
      - plotly==6.0.1
      - polars==1.36.1
      - polars-runtime-32==1.36.1
      - portalocker==3.1.1
      - prompt-toolkit==3.0.51
      - protobuf==5.29.4
      - psutil==7.0.0
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - pydantic==2.11.3
      - pydantic-core==2.33.1
      - pyglet==2.1.3
      - pygments==2.19.1
      - pyopengl==3.1.0
      - pyopengl-accelerate==3.1.9
      - pyparsing==3.2.3
      - pyquaternion==0.9.9
      - pyrender==0.1.45
      - python-dateutil==2.9.0.post0
      - pytorch3d==0.7.8
      - pytz==2025.2
      - qudida==0.0.4
      - referencing==0.36.2
      - retrying==1.3.4
      - rpds-py==0.24.0
      - safetensors==0.5.3
      - scikit-image==0.25.2
      - scikit-learn==1.6.1
      - scipy==1.15.2
      - sentry-sdk==2.26.1
      - setproctitle==1.3.5
      - simsimd==6.2.1
      - six==1.17.0
      - smmap==5.0.2
      - smplfitter==0.2.10
      - smplx==0.1.28
      - stack-data==0.6.3
      - stringzilla==3.12.4
      - sympy==1.13.1
      - threadpoolctl==3.6.0
      - tifffile==2025.3.30
      - timm==1.0.15
      - traitlets==5.14.3
      - trimesh==4.6.8
      - typing-inspection==0.4.0
      - tzdata==2025.2
      - ultralytics==8.3.239
      - ultralytics-thop==2.0.18
      - wandb==0.19.9
      - wcwidth==0.2.13
      - webdataset==0.2.111
      - werkzeug==3.0.6
      - widgetsnbextension==4.0.14
      - zipp==3.21.0
