name: moro
channels:
  - pytorch
  - nvidia
  - defaults
  - conda-forge
dependencies:
  - python=3.11.0
  - pytorch::pytorch=2.4.1
  - pytorch::pytorch-cuda=11.8
  - pytorch::torchvision=0.19.1
  - pytorch::torchaudio=2.4.1
  - pytorch-mutex=1.0
  - pytorch-lightning=2.5.0.post0
  - lightning=2.5.0.post0
  - lightning-utilities=0.11.9
  - torchmetrics=1.2.1
  - numpy=2.0.1
  - pillow=11.1.0
  - requests=2.32.3
  - tqdm=4.67.1
  - yacs=0.1.6
  - networkx=3.4.2
  - pyyaml=6.0.2
  - pip
