# @package _global_

defaults:
  - override /data: video 
  - override /mask_transformer/mask: inference
  
name: MIMO-${model.backbone.type}-${tag}
benchmark: video_train

model:
  task: video
  
  motion_ckpt: motion_pretrain 
  image_ckpt: video_pretrain

  backbone:
    freeze: true

  use_smoother: true

  dst_former:
    freeze_motion: false
    freeze_image: true

dataset:
  batch_size: 2 

  extreme_crop_aug_prob: 0.2

optim:
  lr: 1e-5

trainer:
  max_steps: 60_000
  val_check_interval: 4_000